[package]
name = "pikastore"
version = "0.1.0"
edition = "2021"

[dependencies]
apis = { workspace = true }
services = { workspace = true }
clap = { workspace = true, features = ["derive"]}
tokio.workspace = true