[package]
name = "services"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
sha256.workspace = true
rand.workspace = true
hex.workspace = true
sha1.workspace = true
rusqlite.workspace = true
serde.workspace = true
quick-xml.workspace = true
axum.workspace =true